name: Validate Agents

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r tools/requirements.txt
          pip install -r tools/requirements-dev.txt

      - name: Validate agent definitions
        run: python3 tools/validate_agents.py

      - name: Run integration tests
        run: python3 -m pytest tests/ -v

      - name: Summary
        if: success()
        run: echo "✅ All validations and tests passed"
